/*******************************************************************************
 *                                                                             *
 * This file is generated by BitFontCreator Grayscale v4.5                     *
 * by Iseatech Software   http://www.iseasoft.com/bfc.htm                      *
 *                        support@iseatech.com                                 *
 *                                                                             *
 * Font name: FontAwesome                                                      *
 * Font width: 21 (monospaced font)                                            *
 * Font height: 16                                                             *
 * Encode: Unicode                                                             *
 * Bits Per Pixel: 1 bpp                                                       *
 *                                                                             *
 * Data length: 8 bits                                                         *
 * Invert bits: No                                                             *
 * Data format: Little Endian, Row based, Row preferred, Unpacked              *
 *                                                                             *
 * Create time: 14:40 01-21-2021                                               *
 *******************************************************************************/

#include "bfcfont.h"

/* The following line needs to be included in any file selecting the
   font.
*/
extern const BFC_FONT fontFontAwesome16h;

const UCHAR abc_fontFontAwesome16h_F241[  48] = { /* code F241 */
  0x00,  0x00,  0x00, // .....................
  0x00,  0x00,  0x00, // .....................
  0x00,  0x00,  0x00, // .....................
  0xFF,  0xFF,  0x07, // ###################..
  0x01,  0x00,  0x04, // #.................#..
  0xFD,  0x3F,  0x0C, // #.############....##.
  0xFD,  0x3F,  0x1C, // #.############....###
  0xFD,  0x3F,  0x18, // #.############.....##
  0xFD,  0x3F,  0x18, // #.############.....##
  0xFD,  0x3F,  0x18, // #.############.....##
  0xFD,  0x3F,  0x0C, // #.############....##.
  0xFD,  0x3F,  0x04, // #.############....#..
  0x01,  0x00,  0x04, // #.................#..
  0xFF,  0xFF,  0x07, // ###################..
  0x00,  0x00,  0x00, // .....................
  0x00,  0x00,  0x00  // .....................
};

const BFC_CHARINFO fontFontAwesome16h_CharInfo[1] = {
   {  21,  48, {abc_fontFontAwesome16h_F241} }  /* code F241 */
};

const BFC_FONT_PROP fontFontAwesome16h_Prop1 = {
   0xF241, /* first character */
   0xF241, /* last character  */
   &fontFontAwesome16h_CharInfo[   0],  /* address of first character */
   (const BFC_FONT_PROP *)0				/* pointer to next BFC_FONT_PROP */
};

const BFC_FONT fontFontAwesome16h = {
   0x01020102,  /* font type = FONTTYPE_PROP | LITTLE_ENDIAN | ENCODING_UNICODE | DATALENGTH_8 */
   16,  /* font height in pixels   */
   14,  /* font ascent (baseline) in pixels  */
   0 ,  /* reversed, =0 */
   {&fontFontAwesome16h_Prop1}  
};
