/* USER CODE BEGIN Header */
/**
  ******************************************************************************
  * @file           : main.c
  * @brief          : Main program body
  ******************************************************************************
  * @attention
  *
  * <h2><center>&copy; Copyright (c) 2020 STMicroelectronics.
  * All rights reserved.</center></h2>
  *
  * This software component is licensed by ST under BSD 3-Clause license,
  * the "License"; You may not use this file except in compliance with the
  * License. You may obtain a copy of the License at:
  *                        opensource.org/licenses/BSD-3-Clause
  *
  ******************************************************************************
  */
/* USER CODE END Header */
/* Includes ------------------------------------------------------------------*/
#include "main.h"

/* Private includes ----------------------------------------------------------*/
/* USER CODE BEGIN Includes */
#include "bfcfont.h"
#include "SSD7317.h"
#ifdef USE_FULL_ASSERT
#include <stdio.h>
#endif
#include <string.h>
#include "stdbool.h"
#include "coffee.h"
#include "hairdryer.h"
#include "thermometer.h"
#include "battery-status-full.h"
#include "bluetooth.h"
#include "Tahoma_12h.h"

/* USER CODE END Includes */

/* Private typedef -----------------------------------------------------------*/
/* USER CODE BEGIN PTD */
/* Ring buffer for Remote Procedure Call */
#define RPC_BUF_SIZE 255
typedef struct {
	uint16_t ctr;
	uint8_t  buf[RPC_BUF_SIZE];
}uart_rx_buf;
/* USER CODE END PTD */

/* Private define ------------------------------------------------------------*/
/* USER CODE BEGIN PD */
/* USER CODE END PD */

/* Private macro -------------------------------------------------------------*/
/* USER CODE BEGIN PM */

/* USER CODE END PM */

/* Private variables ---------------------------------------------------------*/
I2C_HandleTypeDef hi2c1;

SPI_HandleTypeDef hspi1;
DMA_HandleTypeDef hdma_spi1_tx;

TIM_HandleTypeDef htim2;

UART_HandleTypeDef huart2;
DMA_HandleTypeDef hdma_usart2_rx;

/* USER CODE BEGIN PV */

//extern const tImage Swim;
/* Buffer for Remote Procedure Call */
uart_rx_buf rpc_rx_buf;

typedef struct ICON{
	const char *name;	 	//name of the icon
	const tImage *image; 	//Pointer to tImage
}icon_t;

#define ICON_MAX	3
/*Array of icons to scroll*/
const icon_t icons[ICON_MAX] = {
		{"Hair Dryer", &hairdryer},
		{"Temperature", &thermometer},
		{"Coffee", &coffee},
};

static int8_t icon_index = 0;
static uint16_t w, h;
static bool pan_active=false;
static bool sleep=false;
/* USER CODE END PV */

/* Private function prototypes -----------------------------------------------*/
void SystemClock_Config(void);
static void MX_GPIO_Init(void);
static void MX_DMA_Init(void);
static void MX_USART2_UART_Init(void);
static void MX_I2C1_Init(void);
static void MX_SPI1_Init(void);
static void MX_TIM2_Init(void);
/* USER CODE BEGIN PFP */
static bool rpc_buffer_empty(void);
static int8_t rpc_get_command(uint8_t *buf, uint16_t *length, uint32_t timeout);

void tone_pwm_set(uint16_t freq);
void tone_pwm_on(void);
void tone_pwm_off(void);

/* USER CODE END PFP */

/* Private user code ---------------------------------------------------------*/
/* USER CODE BEGIN 0 */
/**
 * @brief
 * \b Description:<br>
 * 	This function redirect printf() to UART2 port, i.e. VCP port.
 * \b Pre-requisite:<br>
 *  1. Define a new symbol #USE_FULL_ASSERT under
 *  	Project Properties>C/C++ General>Paths and Symbols>#Symbols>GNU C<br>
 *  2. Need two files: syscalls.c and sysmem.c to work. They are automatically
 *  	generated by STM32CubeIDE if you choose Nucleo Standard EVK as the hw platform
 */
#ifdef USE_FULL_ASSERT
/* @note Override __io_putchar() in syscalls.c */
int __io_putchar(int ch)
{
	HAL_UART_Transmit(&huart2, (uint8_t *)&ch, 1, 0xFFFF);
	return ch;
}
#endif

/**
 * @brief
 * \b	Description:<br>
 * 			This function returns the number of characters in the communication buffer
 * @return 	`true` if the buffer is empty
 * 			`false` if the buffer is not empty, message removal from the receiving buffer is required
 */
static bool rpc_buffer_empty(void)
{
	bool empty = true;

	if(rpc_rx_buf.ctr > 0)
		empty = false;

	return empty;
}

/**
 * @brief
 * \b	Description:<br>
 * 		This function is called to obtain all characters from the
 * 		communication buffer rpc_rx_buf.buf[] to a destination buffer
 * @param 	*buf is a pointer to the buffer you want to store incoming characters.
 * 			Make sure it is large enough to save the characters.
 * 			A safe array size is RPC_BUF_SIZE.
 * @param	*length points to the variable to hold the length of command receive
 * @param	timeout is the CMSIS_RTOS_TimeOutValue or 0 in case of no time-out(wait forever).
 * 			This argument is valid only when FreeRTOS is used.
 * 			For polling method, timeout does not care.
 * @return	If FreeRTOS is used, this is the status code that indicates the
 * 			execution status of the function with the same return code of osSemaphoreAcquire()
 * 			If no FreeRTOS is used, the return value is always 0
 */
static int8_t rpc_get_command(uint8_t *buf, uint16_t *length, uint32_t timeout)
{
	int8_t err = 0;

	*length = 0;

	if(!rpc_buffer_empty()){
		HAL_UART_DMAPause(&huart2);
		*length = rpc_rx_buf.ctr;

		for(uint16_t i=0; i<rpc_rx_buf.ctr; i++){
			*buf++ = rpc_rx_buf.buf[i];
		}
		rpc_rx_buf.ctr = 0; //reset the counter

		HAL_UART_DMAResume(&huart2);
	}

	return err;
}

/**
 * @brief
 * \b	Description:<br>
 *		This function sets PWM frequency for buzzer
 *	@param	freq in Hz (max 10kHz)
 *	@note	hardware dependent, assumed a sysclk frequency of 32MHz
 */
void tone_pwm_set(uint16_t freq)
{
	if (freq>10000) freq=10000;

	uint16_t period = (100000/freq) - 1;

	  TIM_ClockConfigTypeDef sClockSourceConfig = {0};
	  TIM_MasterConfigTypeDef sMasterConfig = {0};
	  TIM_OC_InitTypeDef sConfigOC = {0};

	  /* USER CODE BEGIN TIM2_Init 1 */

	  /* USER CODE END TIM2_Init 1 */
	  htim2.Instance = TIM2;
	  htim2.Init.Prescaler = 320-1;
	  htim2.Init.CounterMode = TIM_COUNTERMODE_UP;
	  htim2.Init.Period = period;
	  htim2.Init.ClockDivision = TIM_CLOCKDIVISION_DIV1;
	  htim2.Init.AutoReloadPreload = TIM_AUTORELOAD_PRELOAD_ENABLE;
	  if (HAL_TIM_Base_Init(&htim2) != HAL_OK)
	  {
	    Error_Handler();
	  }
	  sClockSourceConfig.ClockSource = TIM_CLOCKSOURCE_INTERNAL;
	  if (HAL_TIM_ConfigClockSource(&htim2, &sClockSourceConfig) != HAL_OK)
	  {
	    Error_Handler();
	  }
	  if (HAL_TIM_PWM_Init(&htim2) != HAL_OK)
	  {
	    Error_Handler();
	  }
	  sMasterConfig.MasterOutputTrigger = TIM_TRGO_RESET;
	  sMasterConfig.MasterSlaveMode = TIM_MASTERSLAVEMODE_DISABLE;
	  if (HAL_TIMEx_MasterConfigSynchronization(&htim2, &sMasterConfig) != HAL_OK)
	  {
	    Error_Handler();
	  }
	  sConfigOC.OCMode = TIM_OCMODE_PWM2;
	  sConfigOC.Pulse = period/2;
	  sConfigOC.OCPolarity = TIM_OCPOLARITY_HIGH;
	  sConfigOC.OCFastMode = TIM_OCFAST_DISABLE;
	  if (HAL_TIM_PWM_ConfigChannel(&htim2, &sConfigOC, TIM_CHANNEL_2) != HAL_OK)
	  {
	    Error_Handler();
	  }
	  /* USER CODE BEGIN TIM2_Init 2 */

	  /* USER CODE END TIM2_Init 2 */
	  HAL_TIM_MspPostInit(&htim2);
}

void tone_pwm_on(void)
{
	HAL_TIM_PWM_Start(&htim2, TIM_CHANNEL_2);
}

void tone_pwm_off(void)
{
	HAL_TIM_PWM_Stop(&htim2, TIM_CHANNEL_2);
}

/**
 * @brief
 * \b	Description:<br>
 *		This callback function is called when there is an active -> idle transition
 *		in USART2 IRQ handler (stm32l4xx_it.c). Characters are inserted into the ring buffer
 *		if it has enough room for incoming data from the DMA channel; otherwise, data will be lost.
 *		This function is declared in main.h and called in stm32l4xx.c::USART2_IRQHandler()
 */
void rpc_idle_callback(void)
{
	HAL_UART_DMAStop(&huart2);
	rpc_rx_buf.ctr = (RPC_BUF_SIZE - __HAL_DMA_GET_COUNTER(&hdma_usart2_rx));
	HAL_UART_Receive_DMA(&huart2, rpc_rx_buf.buf, RPC_BUF_SIZE);
}

/* USER CODE END 0 */

/**
  * @brief  The application entry point.
  * @retval int
  */
int main(void)
{
  /* USER CODE BEGIN 1 */

  /* USER CODE END 1 */

  /* MCU Configuration--------------------------------------------------------*/

  /* Reset of all peripherals, Initializes the Flash interface and the Systick. */
  HAL_Init();

  /* USER CODE BEGIN Init */

  /* USER CODE END Init */

  /* Configure the system clock */
  SystemClock_Config();

  /* USER CODE BEGIN SysInit */

  /* USER CODE END SysInit */

  /* Initialize all configured peripherals */
  MX_GPIO_Init();
  MX_DMA_Init();
  MX_USART2_UART_Init();
  MX_I2C1_Init();
  MX_SPI1_Init();
  MX_TIM2_Init();
  /* USER CODE BEGIN 2 */
  ssd7317_init();
  ssd7317_put_string(6,5,&Tahoma_12h,"10:15",0);
  ssd7317_put_image(40,0,&bluetooth,0);
  ssd7317_put_image(70,0,&batterystatusfull,0);

  ssd7317_get_stringsize(&Tahoma_12h, icons[icon_index].name, &w, &h);
  ssd7317_put_string((OLED_HOR_RES-w)/2, (60-h), &Tahoma_12h, icons[icon_index].name, 0);
  ssd7317_put_image(16,64, icons[icon_index].image, 0);

  /* USER CODE END 2 */

  /* Infinite loop */
  /* USER CODE BEGIN WHILE */
  while (1)
  {
    /* USER CODE END WHILE */

    /* USER CODE BEGIN 3 */
	  finger_t finger = ssd7317_get_gesture();

	  switch (finger.gesture){
	  case LONG_TAP_ANYKEY:
		  ssd7317_display_clear(BLACK);
		  tone_pwm_set(500);
		  tone_pwm_on();
		  HAL_Delay(1000);
		  tone_pwm_off();
		  sleep=true;
		  break;
	  case SINGLE_TAP_ANYKEY:
		  if(sleep==true){
			  sleep=false;
			  ssd7317_put_string(6,5,&Tahoma_12h,"10:15",0);
			  ssd7317_put_image(40,0,&bluetooth,0);
			  ssd7317_put_image(70,0,&batterystatusfull,0);
			  ssd7317_get_stringsize(&Tahoma_12h, icons[icon_index].name, &w, &h);
			  ssd7317_put_string((OLED_HOR_RES-w)/2, (60-h), &Tahoma_12h, icons[icon_index].name, 0);
			  ssd7317_put_image(16,64, icons[icon_index].image, 0);
		  }
		  if(pan_active){
			  ssd7317_scroll_brake();
			  pan_active=false;
			  tone_pwm_off();
		  }else{
			  tone_pwm_set(1000);
			  tone_pwm_on();
			  ssd7317_put_image(16,64, icons[icon_index].image, 1);
			  tone_pwm_set(500);
			  HAL_Delay(50);
			  ssd7317_put_image(16,64, icons[icon_index].image, 0);
			  tone_pwm_off();
		  }
		  break;
	  case SWIPE_DOWN:
	  case SWIPE_UP:
		  if(sleep==true){
			  sleep=false;
			  ssd7317_put_string(6,5,&Tahoma_12h,"10:15",0);
			  ssd7317_put_image(40,0,&bluetooth,0);
			  ssd7317_put_image(70,0,&batterystatusfull,0);
		  }
		  if(finger.tap_down_key == finger.tap_up_key){
			  rect_t full_page = {0,0,95,127};
			  ssd7317_scroll_page(full_page,7,5,finger);
			  pan_active = true;
			  tone_pwm_set(200);
			  tone_pwm_on();
		  }else{
			  ssd7317_get_stringsize(&Tahoma_12h, icons[icon_index].name, &w, &h);
			  rect_t erase = {(OLED_HOR_RES-w)/2, 60-h, (OLED_HOR_RES-w)/2 + w -1, 63};
			  ssd7317_fill_color(erase, BLACK);
			  if(finger.gesture==SWIPE_DOWN){
				  if(++icon_index>(ICON_MAX-1)) icon_index=0;
				  ssd7317_get_stringsize(&Tahoma_12h, icons[icon_index].name, &w, &h);
				  ssd7317_put_string((OLED_HOR_RES-w)/2, (60-h), &Tahoma_12h, icons[icon_index].name, 0);
				  ssd7317_scroll_image(16, 64, 64, icons[icon_index].image, finger);
			  }else{
			   //finger.gesture==SWIPE_UP
				  if(--icon_index<0) icon_index=(ICON_MAX-1);
				  ssd7317_get_stringsize(&Tahoma_12h, icons[icon_index].name, &w, &h);
				  ssd7317_put_string((OLED_HOR_RES-w)/2, (60-h), &Tahoma_12h, icons[icon_index].name, 0);
				  ssd7317_get_stringsize(&Tahoma_12h, icons[icon_index].name, &w, &h);
				  ssd7317_scroll_image(16, 64, 0, icons[icon_index].image, finger);
			  }
		  }
		  break;
	  }

	  /**
	   * Remote Procedure Call section below
	   */

		  uint16_t length;
		  uint8_t msg[RPC_BUF_SIZE];
		  rpc_get_command(msg, &length, 0);

		  if(length){
		#ifdef USE_FULL_ASSERT
			  printf("Command received:\r\n");
			  for(uint8_t i=0; i<length; i++)
			  {
				  printf("%c", msg[i]);
			  }
			  printf("\r\n");
		#endif
			  if(length>2){
				if(msg[0]==0x7E && (msg[1]=='c')) //0x7E 0x63
				{
					printf("SPI command sending.\r\n");
					spi_write_command((const uint8_t *)&msg[2], length-2);
				}
				if(msg[0]==0x7E && (msg[1]=='d')) //0x7E 0x64
				{
					printf("SPI data sending.\r\n");
					spi_write_data((const uint8_t *)&msg[2], length-2);
				}
			  }
			  memset(msg, 0x00, length);
		  }
  }


  /* USER CODE END 3 */
}

/**
  * @brief System Clock Configuration
  * @retval None
  */
void SystemClock_Config(void)
{
  RCC_OscInitTypeDef RCC_OscInitStruct = {0};
  RCC_ClkInitTypeDef RCC_ClkInitStruct = {0};
  RCC_PeriphCLKInitTypeDef PeriphClkInit = {0};

  /** Initializes the RCC Oscillators according to the specified parameters
  * in the RCC_OscInitTypeDef structure.
  */
  RCC_OscInitStruct.OscillatorType = RCC_OSCILLATORTYPE_MSI;
  RCC_OscInitStruct.MSIState = RCC_MSI_ON;
  RCC_OscInitStruct.MSICalibrationValue = 0;
  RCC_OscInitStruct.MSIClockRange = RCC_MSIRANGE_6;
  RCC_OscInitStruct.PLL.PLLState = RCC_PLL_ON;
  RCC_OscInitStruct.PLL.PLLSource = RCC_PLLSOURCE_MSI;
  RCC_OscInitStruct.PLL.PLLM = 1;
  RCC_OscInitStruct.PLL.PLLN = 16;
  RCC_OscInitStruct.PLL.PLLP = RCC_PLLP_DIV7;
  RCC_OscInitStruct.PLL.PLLQ = RCC_PLLQ_DIV2;
  RCC_OscInitStruct.PLL.PLLR = RCC_PLLR_DIV2;
  if (HAL_RCC_OscConfig(&RCC_OscInitStruct) != HAL_OK)
  {
    Error_Handler();
  }
  /** Initializes the CPU, AHB and APB buses clocks
  */
  RCC_ClkInitStruct.ClockType = RCC_CLOCKTYPE_HCLK|RCC_CLOCKTYPE_SYSCLK
                              |RCC_CLOCKTYPE_PCLK1|RCC_CLOCKTYPE_PCLK2;
  RCC_ClkInitStruct.SYSCLKSource = RCC_SYSCLKSOURCE_PLLCLK;
  RCC_ClkInitStruct.AHBCLKDivider = RCC_SYSCLK_DIV1;
  RCC_ClkInitStruct.APB1CLKDivider = RCC_HCLK_DIV1;
  RCC_ClkInitStruct.APB2CLKDivider = RCC_HCLK_DIV1;

  if (HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_1) != HAL_OK)
  {
    Error_Handler();
  }
  PeriphClkInit.PeriphClockSelection = RCC_PERIPHCLK_USART2|RCC_PERIPHCLK_I2C1;
  PeriphClkInit.Usart2ClockSelection = RCC_USART2CLKSOURCE_PCLK1;
  PeriphClkInit.I2c1ClockSelection = RCC_I2C1CLKSOURCE_PCLK1;
  if (HAL_RCCEx_PeriphCLKConfig(&PeriphClkInit) != HAL_OK)
  {
    Error_Handler();
  }
  /** Configure the main internal regulator output voltage
  */
  if (HAL_PWREx_ControlVoltageScaling(PWR_REGULATOR_VOLTAGE_SCALE1) != HAL_OK)
  {
    Error_Handler();
  }
}

/**
  * @brief I2C1 Initialization Function
  * @param None
  * @retval None
  */
static void MX_I2C1_Init(void)
{

  /* USER CODE BEGIN I2C1_Init 0 */

  /* USER CODE END I2C1_Init 0 */

  /* USER CODE BEGIN I2C1_Init 1 */

  /* USER CODE END I2C1_Init 1 */
  hi2c1.Instance = I2C1;
  hi2c1.Init.Timing = 0x00707CBB;
  hi2c1.Init.OwnAddress1 = 0;
  hi2c1.Init.AddressingMode = I2C_ADDRESSINGMODE_7BIT;
  hi2c1.Init.DualAddressMode = I2C_DUALADDRESS_DISABLE;
  hi2c1.Init.OwnAddress2 = 0;
  hi2c1.Init.OwnAddress2Masks = I2C_OA2_NOMASK;
  hi2c1.Init.GeneralCallMode = I2C_GENERALCALL_DISABLE;
  hi2c1.Init.NoStretchMode = I2C_NOSTRETCH_DISABLE;
  if (HAL_I2C_Init(&hi2c1) != HAL_OK)
  {
    Error_Handler();
  }
  /** Configure Analogue filter
  */
  if (HAL_I2CEx_ConfigAnalogFilter(&hi2c1, I2C_ANALOGFILTER_ENABLE) != HAL_OK)
  {
    Error_Handler();
  }
  /** Configure Digital filter
  */
  if (HAL_I2CEx_ConfigDigitalFilter(&hi2c1, 0) != HAL_OK)
  {
    Error_Handler();
  }
  /* USER CODE BEGIN I2C1_Init 2 */

  /* USER CODE END I2C1_Init 2 */

}

/**
  * @brief SPI1 Initialization Function
  * @param None
  * @retval None
  */
static void MX_SPI1_Init(void)
{

  /* USER CODE BEGIN SPI1_Init 0 */

  /* USER CODE END SPI1_Init 0 */

  /* USER CODE BEGIN SPI1_Init 1 */

  /* USER CODE END SPI1_Init 1 */
  /* SPI1 parameter configuration*/
  hspi1.Instance = SPI1;
  hspi1.Init.Mode = SPI_MODE_MASTER;
  hspi1.Init.Direction = SPI_DIRECTION_1LINE;
  hspi1.Init.DataSize = SPI_DATASIZE_8BIT;
  hspi1.Init.CLKPolarity = SPI_POLARITY_LOW;
  hspi1.Init.CLKPhase = SPI_PHASE_1EDGE;
  hspi1.Init.NSS = SPI_NSS_HARD_OUTPUT;
  hspi1.Init.BaudRatePrescaler = SPI_BAUDRATEPRESCALER_2;
  hspi1.Init.FirstBit = SPI_FIRSTBIT_MSB;
  hspi1.Init.TIMode = SPI_TIMODE_DISABLE;
  hspi1.Init.CRCCalculation = SPI_CRCCALCULATION_DISABLE;
  hspi1.Init.CRCPolynomial = 7;
  hspi1.Init.CRCLength = SPI_CRC_LENGTH_DATASIZE;
  hspi1.Init.NSSPMode = SPI_NSS_PULSE_ENABLE;
  if (HAL_SPI_Init(&hspi1) != HAL_OK)
  {
    Error_Handler();
  }
  /* USER CODE BEGIN SPI1_Init 2 */

  /* USER CODE END SPI1_Init 2 */

}

/**
  * @brief TIM2 Initialization Function
  * @param None
  * @retval None
  */
static void MX_TIM2_Init(void)
{

  /* USER CODE BEGIN TIM2_Init 0 */

  /* USER CODE END TIM2_Init 0 */

  TIM_ClockConfigTypeDef sClockSourceConfig = {0};
  TIM_MasterConfigTypeDef sMasterConfig = {0};
  TIM_OC_InitTypeDef sConfigOC = {0};

  /* USER CODE BEGIN TIM2_Init 1 */

  /* USER CODE END TIM2_Init 1 */
  htim2.Instance = TIM2;
  htim2.Init.Prescaler = 320-1;
  htim2.Init.CounterMode = TIM_COUNTERMODE_UP;
  htim2.Init.Period = 100-1;
  htim2.Init.ClockDivision = TIM_CLOCKDIVISION_DIV1;
  htim2.Init.AutoReloadPreload = TIM_AUTORELOAD_PRELOAD_ENABLE;
  if (HAL_TIM_Base_Init(&htim2) != HAL_OK)
  {
    Error_Handler();
  }
  sClockSourceConfig.ClockSource = TIM_CLOCKSOURCE_INTERNAL;
  if (HAL_TIM_ConfigClockSource(&htim2, &sClockSourceConfig) != HAL_OK)
  {
    Error_Handler();
  }
  if (HAL_TIM_PWM_Init(&htim2) != HAL_OK)
  {
    Error_Handler();
  }
  sMasterConfig.MasterOutputTrigger = TIM_TRGO_RESET;
  sMasterConfig.MasterSlaveMode = TIM_MASTERSLAVEMODE_DISABLE;
  if (HAL_TIMEx_MasterConfigSynchronization(&htim2, &sMasterConfig) != HAL_OK)
  {
    Error_Handler();
  }
  sConfigOC.OCMode = TIM_OCMODE_PWM2;
  sConfigOC.Pulse = 0;
  sConfigOC.OCPolarity = TIM_OCPOLARITY_HIGH;
  sConfigOC.OCFastMode = TIM_OCFAST_DISABLE;
  if (HAL_TIM_PWM_ConfigChannel(&htim2, &sConfigOC, TIM_CHANNEL_2) != HAL_OK)
  {
    Error_Handler();
  }
  /* USER CODE BEGIN TIM2_Init 2 */

  /* USER CODE END TIM2_Init 2 */
  HAL_TIM_MspPostInit(&htim2);

}

/**
  * @brief USART2 Initialization Function
  * @param None
  * @retval None
  */
static void MX_USART2_UART_Init(void)
{

  /* USER CODE BEGIN USART2_Init 0 */

  /* USER CODE END USART2_Init 0 */

  /* USER CODE BEGIN USART2_Init 1 */

  /* USER CODE END USART2_Init 1 */
  huart2.Instance = USART2;
  huart2.Init.BaudRate = 115200;
  huart2.Init.WordLength = UART_WORDLENGTH_8B;
  huart2.Init.StopBits = UART_STOPBITS_1;
  huart2.Init.Parity = UART_PARITY_NONE;
  huart2.Init.Mode = UART_MODE_TX_RX;
  huart2.Init.HwFlowCtl = UART_HWCONTROL_NONE;
  huart2.Init.OverSampling = UART_OVERSAMPLING_16;
  huart2.Init.OneBitSampling = UART_ONE_BIT_SAMPLE_DISABLE;
  huart2.AdvancedInit.AdvFeatureInit = UART_ADVFEATURE_NO_INIT;
  if (HAL_UART_Init(&huart2) != HAL_OK)
  {
    Error_Handler();
  }
  /* USER CODE BEGIN USART2_Init 2 */
  rpc_rx_buf.ctr = 0;
  __HAL_UART_ENABLE_IT(&huart2, UART_IT_IDLE);
  if(HAL_UART_Receive_DMA(&huart2, rpc_rx_buf.buf, RPC_BUF_SIZE)!=HAL_OK)
  	{
  		Error_Handler();
  	}
  /* USER CODE END USART2_Init 2 */

}

/**
  * Enable DMA controller clock
  */
static void MX_DMA_Init(void)
{

  /* DMA controller clock enable */
  __HAL_RCC_DMA1_CLK_ENABLE();

  /* DMA interrupt init */
  /* DMA1_Channel3_IRQn interrupt configuration */
  HAL_NVIC_SetPriority(DMA1_Channel3_IRQn, 6, 0);
  HAL_NVIC_EnableIRQ(DMA1_Channel3_IRQn);
  /* DMA1_Channel6_IRQn interrupt configuration */
  HAL_NVIC_SetPriority(DMA1_Channel6_IRQn, 0, 0);
  HAL_NVIC_EnableIRQ(DMA1_Channel6_IRQn);

}

/**
  * @brief GPIO Initialization Function
  * @param None
  * @retval None
  */
static void MX_GPIO_Init(void)
{
  GPIO_InitTypeDef GPIO_InitStruct = {0};

  /* GPIO Ports Clock Enable */
  __HAL_RCC_GPIOA_CLK_ENABLE();
  __HAL_RCC_GPIOB_CLK_ENABLE();

  /*Configure GPIO pin Output Level */
  HAL_GPIO_WritePin(OLED_DC_GPIO_Port, OLED_DC_Pin, GPIO_PIN_RESET);

  /*Configure GPIO pin Output Level */
  HAL_GPIO_WritePin(TCH_TRES_GPIO_Port, TCH_TRES_Pin, GPIO_PIN_RESET);

  /*Configure GPIO pin : OLED_FR_Pin */
  GPIO_InitStruct.Pin = OLED_FR_Pin;
  GPIO_InitStruct.Mode = GPIO_MODE_IT_RISING;
  GPIO_InitStruct.Pull = GPIO_PULLUP;
  HAL_GPIO_Init(OLED_FR_GPIO_Port, &GPIO_InitStruct);

  /*Configure GPIO pin : OLED_DC_Pin */
  GPIO_InitStruct.Pin = OLED_DC_Pin;
  GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
  GPIO_InitStruct.Pull = GPIO_NOPULL;
  GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_HIGH;
  HAL_GPIO_Init(OLED_DC_GPIO_Port, &GPIO_InitStruct);

  /*Configure GPIO pin : TCH_TRES_Pin */
  GPIO_InitStruct.Pin = TCH_TRES_Pin;
  GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
  GPIO_InitStruct.Pull = GPIO_NOPULL;
  GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
  HAL_GPIO_Init(TCH_TRES_GPIO_Port, &GPIO_InitStruct);

  /*Configure GPIO pin : TCH_IRQ_Pin */
  GPIO_InitStruct.Pin = TCH_IRQ_Pin;
  GPIO_InitStruct.Mode = GPIO_MODE_IT_FALLING;
  GPIO_InitStruct.Pull = GPIO_PULLUP;
  HAL_GPIO_Init(TCH_IRQ_GPIO_Port, &GPIO_InitStruct);

  /* EXTI interrupt init*/
  HAL_NVIC_SetPriority(EXTI0_IRQn, 0, 0);
  HAL_NVIC_EnableIRQ(EXTI0_IRQn);

  HAL_NVIC_SetPriority(EXTI15_10_IRQn, 0, 0);
  HAL_NVIC_EnableIRQ(EXTI15_10_IRQn);

}

/* USER CODE BEGIN 4 */

/* USER CODE END 4 */

/**
  * @brief  This function is executed in case of error occurrence.
  * @retval None
  */
void Error_Handler(void)
{
  /* USER CODE BEGIN Error_Handler_Debug */
  /* User can add his own implementation to report the HAL error return state */

  /* USER CODE END Error_Handler_Debug */
}

#ifdef  USE_FULL_ASSERT
/**
  * @brief  Reports the name of the source file and the source line number
  *         where the assert_param error has occurred.
  * @param  file: pointer to the source file name
  * @param  line: assert_param error line source number
  * @retval None
  */
void assert_failed(uint8_t *file, uint32_t line)
{
  /* USER CODE BEGIN 6 */
  //   printf("Wrong parameters value: file %s on line %d\r\n", file, line);
  /* USER CODE END 6 */
}
#endif /* USE_FULL_ASSERT */

/************************ (C) COPYRIGHT STMicroelectronics *****END OF FILE****/
